version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      weekly-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      weekly-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      weekly-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      weekly-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "npm"
    directory: "/app/frontend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      weekly-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      weekly-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "uv"
    directory: "/app"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      weekly-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      weekly-major:
        patterns:
          - "*"
        update-types:
          - "major"
