version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/app/frontend"
    schedule:
      interval: "weekly"
    groups:
      jest:
        patterns:
          - "jest"
          - "jest-environment-jsdom"
      next:
        patterns:
          - "eslint-config-next"
          - "next"
          - "@next/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
