debug = "1"
enable-prometheus = "1"

default-python-version = "3.13"
python-versions = ["3.9", "3.10", "3.11", "3.12", "3.13"]
mypy-versions = [
    ["mypy latest", "latest"],
    ["basedmypy latest", "basedmypy-latest"],
]

# Example to use Cloud Functions
# sandbox = "mypy_playground.sandbox.cloud_functions.CloudFunctionsSandbox"
cloud-functions-base-url = "https://REGION-PROJECT.cloudfunctions.net"
# We can issue one using CLI: gcloud auth print-identity-token
cloud-functions-identity-token = "TOKEN"

[cloud-functions-names]
latest = "mypy-latest"
"basedmypy latest" = "basedmypy-latest"

[docker-images]
latest = "ymyzk/mypy-playground-sandbox:latest"
"basedmypy latest" = "ymyzk/mypy-playground-sandbox:basedmypy-latest"
