FROM python:3.6-slim

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            gcc \
            libc6-dev \
        && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.uwsgi.txt /app/
WORKDIR /app
RUN pip install -r requirements.txt -r requirements.uwsgi.txt \
        && rm -rf /root/.cache

COPY . /app

EXPOSE 8080
CMD ["uwsgi", "--http", ":8080", "--wsgi-file", "app.py"]
