name: Check and add new mypy version

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: Python version
        required: true
        type: string
        default: "3.13"

permissions:
  contents: write
  pull-requests: write

jobs:
  add-mypy-version:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Inputs:"
          echo "  Python version: $PYTHON_VERSION"
        env:
          PYTHON_VERSION: ${{ github.event.inputs.python_version }}

      - uses: actions/checkout@v4

      - name: Find new versions
        id: find_new_versions
        run: |
          NEW_VERSION=$(./find_new_versions.sh mypy | head -n 1)
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          if [ -n "$NEW_VERSION" ]; then
            echo "Found new mypy version: $NEW_VERSION"
          else
            echo "No new mypy version found"
            echo "::error::No new mypy version found"
            exit 1
          fi
        working-directory: ./sandbox

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Set up pip-tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pip-tools

      - name: Add mypy version and update latest tag
        run: |
          ./add_version.sh ${{ steps.find_new_versions.outputs.new_version }}
          ./update_latest.sh ${{ steps.find_new_versions.outputs.new_version }}
        working-directory: ./sandbox

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Add mypy ${{ steps.find_new_versions.outputs.new_version }}
            committer: GitHub <noreply@github.com>
            author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            signoff: false
            branch: mypy-${{ steps.find_new_versions.outputs.new_version }}
            delete-branch: true
            title: Add mypy ${{ steps.find_new_versions.outputs.new_version }}
            body: |
              - Add mypy ${{ steps.find_new_versions.outputs.new_version }}
              - Update latest tag
            draft: false
