name: CI
on:
  push:
    branches:
      - master
  pull_request:
env:
  APP_IMAGE_NAME: ymyzk/mypy-playground
  SANDBOX_IMAGE_NAME: ymyzk/mypy-playground-sandbox
  DOCKER_BUILDKIT: 1
jobs:
  test_app:
    needs:
      - test_frontend
    name: Test app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14']
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
      with:
        name: frontend
        path: app/static
    - name: Install uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --frozen
      working-directory: ./app
    - name: Run type checking
      run: uv run mypy .
      working-directory: ./app
    - name: Run pre-commit
      run: uv run pre-commit run --all-files
      working-directory: ./app
    - name: Run tests
      run: uv run pytest
      working-directory: ./app

  test_frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x, 25.x]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: ./app/frontend
    - name: Build, lint, and test frontend
      run: |
        npm run build
        npm run format:ci
        npm run lint
        npm run test:ci
      working-directory: ./app/frontend
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: matrix.node-version == '24.x'
      with:
        name: frontend
        path: app/frontend/dist

  build_docker_images:
    name: Build and push Docker images
    needs:
      - test_app
      - test_frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: docker version
      - name: Build app image for development
        run: docker build --pull -t app:dev -f ./app/dockerfile/dev/Dockerfile ./app
      - name: Build app image for production
        run: docker build --pull -t app:latest -f ./app/dockerfile/prod/Dockerfile ./app
      - name: Build latest Docker sandbox image
        run: docker build -t sandbox:latest ./sandbox/docker/latest
      - name: Build Docker sandbox images
        run: ./sandbox/docker/build.sh $SANDBOX_IMAGE_NAME
      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push app image
        run: |
          docker tag app:latest $APP_IMAGE_NAME:latest
          docker push $APP_IMAGE_NAME:latest
      - name: Push Docker sandbox images
        run: ./sandbox/docker/push.sh $SANDBOX_IMAGE_NAME

  dependabot:
    runs-on: ubuntu-latest
    needs:
      - test_app
      - test_frontend
    permissions:
      contents: write
      pull-requests: write
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    name: Automatically merge Dependabot PRs
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs (patch)
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs (minor)
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' && (contains(steps.metadata.outputs.dependency-names, '@types/'))
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
